version: '3'
# services definition
services:
# django backend login app service
  auth_app:
    build: ./auth
    environment:
      - SECRET_KEY=0!ff!7n6dmbcj-!h(#+phg==a50tn8g2qws7p_fg9syiw$rn*w
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=s@tfin2021
      - DB_SERVICE=db
      - DB_PORT=5432
    ports:
      - 80:80
    depends_on:
      - db
# carto front end service definition    
  carto_front_end:
    build:
      context: ./carto_front_end
    image: carto-ui
    container_name: carto-ui
    ports:
      - 80:80
    depends_on:
      - proxy

#react frontend login service
  login_app:
    build: 
      context: ./loginapp
    image: login-frontend
    container_name: login-frontend
    ports:
      - 80:80
    depends_on:
      - auth_app

# postrges sql db service
  db: 
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=s@tfin2021
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#nginx proxy service
  proxy:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth_app
      - carto_front_end

volumes:
  pgdata:
